import { Inter } from "next/font/google";
import './globals.css'
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config'
import Web3ModalProvider from '@/context'
import { DataContextProvider } from "@/context/data";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}


export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <Web3ModalProvider initialState={initialState}>
      <DataContextProvider>
        <html lang="en">
          <body>
            {children}
          </body>
        </html>
      </DataContextProvider>
    </Web3ModalProvider>
  )
}